spring:
  application:
    name: gulimall-third-party
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    alicloud:
      access-key: LTAI4G48MqwT9TV6kaP8SUBD
      secret-key: 27jEEpRuq3eSDQEBizdHOzzBb3cRRf
      oss:
        endpoint: oss-cn-beijing.aliyuncs.com
        bucket: gulimall-66

server:
  port: 30000