spring:
  application:
    name: gulimall-third-party
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    alicloud:
      access-key:
      secret-key:
      oss:
        endpoint: oss-cn-beijing.aliyuncs.com
        bucket: gulimall-66
      sms:
        host: https://gyytz.market.alicloudapi.com
        path: /sms/smsSend
        smsSignId: 2e65b1bb3d054466b82f0c9d125465e2
        templateId: 908e94ccf08b4476ba6c876d13f084ad
        appcode: 81170d1f9f0f433aaf45da23a2e49972
server:
  port: 30000